version: '3.8'

# 服务通用日志配置
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

# docker网络配置
networks:
  luban-network:
#    external: true  # 表明网络是外部已存在的
    driver: bridge  # 默认驱动bridge，可不填写，执行up是自动创建内部管理网络
# 老版本/独立插件：使用docker-compose，新版本/深度集成：使用docker compose（可以兼容旧版本，使用docker-compose）
# 拉取镜像（若本地无镜像，Docker 会自动从私有仓库拉取）：docker-compose -f docker-compose.env.yml pull
# 启动服务： docker-compose -f docker-compose.env.yml up -d
# 停止服务并删除容器及关联网络和匿名卷： docker-compose -f docker-compose.env.yml down
# 停止服务： docker-compose -f docker-compose.env.yml stop
# 删除已停止的容器： docker-compose -f docker-compose.env.yml rm -f
# 查看是否加入网络：docker network inspect luban-network
services:

  #windows
#  mkdir "data\nacos_data"
#  mkdir "data\mysql_data"
#  mkdir "data\openldap_data"
#  docker run -d --name nacos -p 8848:8848 -p 9848:9848 -p 9849:9849 --restart=always nacos/nacos-server:v2.3.2
#   http://localhost:8848/nacos
#   导入配置文件
#  docker cp nacos:/home/nacos/conf ./data/nacos_data
#  docker cp nacos:/home/nacos/data ./data/nacos_data
#  docker cp nacos:/home/nacos/logs ./data/nacos_data
#  docker stop nacos
#  docker rm nacos
#  docker  compose -f docker-compose.env.yml up -d
#  docker cp ./init/openldap_init/init.ldif luban-openldap-demo:/tmp/init.ldif
#  docker exec luban-openldap-demo ldapadd -x -D "cn=admin,dc=ddlnt,dc=xyz" -w ldapPassword -f /tmp/init.ldif

  #linus
#  cd /home
#  mkdir -p luban_springcloud_demo/data/nacos_data
#  mkdir -p luban_springcloud_demo/data/mysql_data
#  cd luban_springcloud_demo
#  unzip init.zip
#  rm init.zip
#  docker run -d --name luban-nacos-demo -e MODE=standalone -p 8848:8848 -p 9848:9848 -p 9849:9849  nacos/nacos-server:v2.3.2
#   http://localhost:8848/nacos
#   导入配置文件
#  docker cp luban-nacos-demo:/home/nacos/conf ./data/nacos_data
#  docker cp luban-nacos-demo:/home/nacos/data ./data/nacos_data
#  docker cp luban-nacos-demo:/home/nacos/logs ./data/nacos_data
#  docker stop luban-nacos-demo
#  docker rm luban-nacos-demo
#  docker-compose -f docker-compose.env.yml pull
#  docker-compose -f docker-compose.env.yml up -d
#  docker cp ./init/openldap_init/init.ldif luban-openldap-demo:/tmp/init.ldif
#  docker exec luban-openldap-demo ldapadd -x -D "cn=admin,dc=ddlnt,dc=xyz" -w ldapPassword -f /tmp/init.ldif


# 一、环境依赖
  # 服务注册与配置管理中心
  luban-nacos-demo:
    image: nacos/nacos-server:v2.3.2
    container_name: luban-nacos-demo
    environment:
      - PREFER_HOST_MODE=luban-nacos-demo  # 主机名
      - MODE=standalone  # 单机点模式
      - TZ=Asia/Shanghai  # 控制时区
    ports:
      - 8848:8848
      - 9848:9848
      - 9849:9849
    volumes:
      - ./data/nacos_data/conf:/home/nacos/conf
      - ./data/nacos_data/data:/home/nacos/data
      - ./data/nacos_data/logs:/home/nacos/logs
    restart: always
    logging: *default-logging
    networks:
      - luban-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/actuator/health"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 5s


#  SHOW TABLE STATUS FROM luban_demo_db LIKE 'product';
#  SHOW FULL COLUMNS FROM product;
#
#  SHOW VARIABLES LIKE 'character_set_%';
  luban-mysql-demo:
    image: mysql:8.0.36
    container_name: luban-mysql-demo
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # root密码
      MYSQL_DATABASE: luban_demo_db      # 初始数据库名
      MYSQL_USER: luban_user_demo                # 创建用户
      MYSQL_PASSWORD: user_password       # 用户密码
      TZ: Asia/Shanghai                  # 设置时区为北京时间
    volumes:
      - ./data/mysql_data:/var/lib/mysql
      - ./init/mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql  # 将init.sql挂载到容器初始化目录
    logging: *default-logging
    networks:
      - luban-network

  luban-redis-demo:
      image: redis:6.2.6
      container_name: luban-redis-demo
      ports:
        - "6379:6379"
      logging: *default-logging
      networks:
        - luban-network

# 初始化文件未启动，手动导入
#  docker cp ./init/openldap_init/init.ldif luban-openldap-demo:/tmp/init.ldif
#  docker exec luban-openldap-demo ldapadd -x -D "cn=admin,dc=ddlnt,dc=xyz" -w ldapPassword -f /tmp/init.ldif

  # LDAP服务
  luban-openldap-demo:
    image: osixia/openldap:1.5.0
    container_name: luban-openldap-demo
    restart: always
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "ldap"   ### 组织名称
      LDAP_DOMAIN: "ddlnt.xyz"    ### 域名
      LDAP_BASE_DN: "dc=ddlnt,dc=xyz"   ### 根据域名组成
      LDAP_ADMIN_PASSWORD: "ldapPassword"   ### 密码设置
      LDAP_CONFIG_PASSWORD: "ldapPassword"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
#      LDAP_INITLDIF_FILE_1: "/container/service/slapd/assets/ldif/custom/init.ldif"
    tty: true
    stdin_open: true
    volumes:
      - ./init/openldap_init/init.ldif:/container/service/slapd/assets/ldif/custom/init.ldif

#      - /data/openldap_data/ldap:/var/lib/ldap
#      - /data/openldap_data/slapd.d:/etc/ldap/slapd.d
#      - /data/openldap_data/certs:/container/service/lapd/assets/certs
    ports:
      - "389:389"
      - "636:636"
    domainname: "ddlnt.xyz"
    hostname: "ldap-server"
    networks:
      - luban-network

#  luban-phpldapadmin-demo:
#    image: osixia/phpldapadmin:latest
#    container_name: luban-phpldapadmin-demo
#    restart: always
#    environment:
#      PHPLDAPADMIN_LDAP_HOSTS: luban-openldap-demo   ### 如果部署后登录不进去有可能是这里出了问题，换为部署openldap服务的公网IP试试
#      PHPLDAPADMIN_HTTPS: "false"
#    ports:
#      - "50081:80"
#    depends_on:
#      - luban-openldap-demo
#    networks:
#      - luban-network
#
#  luban-self-service-password-demo:
#    image: tiredofit/self-service-password:latest
#    container_name: luban-self-service-password-demo
#    restart: always
#    ports:
#      - "50080:80"
#    environment:
#      - LDAP_SERVER=ldap://openldap:389
#      - LDAP_BINDDN=cn=admin,dc=ddlnt,dc=xyz #默认是cn=admin,dc=wkx,dc=cn
#      - LDAP_BINDPASS=ldapPassword
#      - LDAP_BASE_SEARCH=dc=ddlnt,dc=xyz
#      - MAIL_FROM=smtp.163.com
#      - MAIL_FROM_NAME=账号自助服务平台
#      - SMTP_DEBUG=0
#      - SMTP_HOST=smtp.163.com
#      - SMTP_USER=wkx323@163.com
#      - SMTP_PASS=HTGCMxxFVLASxxxxRS
#      - SMTP_PORT=465
#      - SMTP_SECURE_TYPE=ssl
#      - SMTP_AUTH_ON=true
#      - NOTIFY_ON_CHANGE=true
##    volumes:
##      - /data/openldap_data/self-service-password/localtime:/etc/localtime
##      - /data/openldap_data/self-service-password/htdocs:/www/ssp
##      - /data/openldap_data/self-service-password/logs:/www/logs
#    networks:
#      - luban-network